### ISSUE TITLE
ERROR:bokeh.server.protocol_handler:error handling message Message 'PATCH-DOC' (revision 1)

### ISSUE THREAD

**Issue by ONISniperOne** [cbouy/DashMD#1]
Installed ok. When first trying to launch dashmd, had to change in template.py of bokeh line 43

from jinja2 import Environment, Markup, FileSystemLoader >
from jinja2 import Environment, FileSystemLoader
from markupsafe import Markup

After that, dashmd launched in browser. Put abs path in "Path to MD directory containing mdin and mdout files" box but got this error in terminal

ERROR:bokeh.server.protocol_handler:error handling message Message 'PATCH-DOC' (revision 1) content: {'events': [{'kind': 'ModelChanged', 'model': {'type': 'Toggle', 'id': '1003'}, 'attr': 'active', 'new': True}], 'references': []}: FileNotFoundError(2, 'No such file or directory')

I think there was a keyerror somewhere?
https://discourse.bokeh.org/t/problem-error-bokeh-server-protocol-handler-error-handling-message-message-patch-doc-revision-1/4058

Thank you for yoru work

**Comment by cbouy** [comment]
I last updated this library ~4 years ago and since then some of the underlying packages have changed quite a bit so it can be considered pretty much a dead project at this point.
The error message seems to indicate a `FileNotFoundError`, if I recall correctly it's not necessary to enter the full abs path to the MD dir, you can navigate there from your terminal, run `dashmd` and then just enter `./` as the path in the box.
If that doesn't work I can't really help more as I can only maintain a limited number of libraries on my free time :/

**Comment by ONISniperOne** [comment]
I double checked the inputs and it was because I paired the wrong prmtop (w/o water) with my trajectory. Everything works just not the RMSD. 

Thank you for your hard work.
